// Code generated by generate_dbs.py. DO NOT EDIT.

package saucenao

// These are database index constants.
const (
	Pixiv    DBMask = 1 << 5
	Danbooru DBMask = 1 << 9
	Yandere  DBMask = 1 << 12
	Gelbooru DBMask = 1 << 25
	Konachan DBMask = 1 << 26
)
